app/models.py
from app import db, login
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(150), unique=True, nullable=False)
    password_hash = db.Column(db.String(150), nullable=False)
    points = db.Column(db.Integer, default=0)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)
    
@login.user_loader
def load_user(id):
    return User.query.get(int(id))


class Room(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150), unique=True, nullable=False)
    password_hash = db.Column(db.String(150), nullable=False)
    users = db.relationship('User', secondary='room_users', backref='rooms')
    owner_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    owner = db.relationship('User', backref='owned_rooms')

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)    

room_users = db.Table('room_users',
    db.Column('room_id', db.Integer, db.ForeignKey('room.id'), primary_key=True),
    db.Column('user_id', db.Integer, db.ForeignKey('user.id'), primary_key=True)
)

app/game/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, ValidationError
from app.models import Room

class CreateRoomForm(FlaskForm):
    name = StringField('Room Name', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Create Room')

    def validate_name(self, name):
        room = Room.query.filter_by(name=name.data).first()
        if room is not None:
            raise ValidationError('Please use a different room name.')

class JoinRoomForm(FlaskForm):
    name = StringField('Room Name', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Join Room')

app/__init__.py
from flask import Flask, render_template, flash, redirect, url_for
from flask import redirect, url_for
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_socketio import SocketIO
from config import Config

db = SQLAlchemy()
login = LoginManager()
login.login_view = 'auth.login'
socketio = SocketIO()

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    login.init_app(app)
    socketio.init_app(app, cors_allowed_origins="*")  # Dodaj obsługę CORS, jeśli potrzebujesz

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    from app.game import bp as game_bp
    app.register_blueprint(game_bp, url_prefix='/game')

    with app.app_context():
        db.create_all()

    @app.route('/')
    def index():
        return render_template('home.html')

    return app

if __name__ == '__main__':
    app = create_app()
    socketio.run(app, debug=True)


app/game/__init__.py
from flask import Blueprint

bp = Blueprint('game', __name__)

from app.game import routes

app/game/routes.py
from flask import render_template, flash, redirect, url_for, request
from flask_login import current_user, login_required
from app import db, socketio
from app.game import bp
from app.game.forms import CreateRoomForm, JoinRoomForm
from app.models import User, Room, room_users
from textblob import Word

def is_english_word(word):
    return Word(word).spellcheck()[0][1] == 1.0



@bp.route('/create_room', methods=['GET', 'POST'])
@login_required
def create_room():
    form = CreateRoomForm()
    if form.validate_on_submit():
        room = Room(name=form.name.data, owner=current_user)
        room.set_password(form.password.data)
        room.users.append(current_user)
        db.session.add(room)
        db.session.commit()
        flash('Room created successfully!')
        return redirect(url_for('game.room', room_id=room.id))
    return render_template('create_room.html', form=form)


@bp.route('/join_room', methods=['GET', 'POST'])
@login_required
def join_room():
    form = JoinRoomForm()
    if form.validate_on_submit():
        room = Room.query.filter_by(name=form.name.data).first()
        if room and room.check_password(form.password.data):
            if len(room.users) < 10:
                room.users.append(current_user)
                db.session.commit()
                flash('Joined room successfully!')
                return redirect(url_for('game.room', room_id=room.id))
            else:
                flash('Room is full!')
        else:
            flash('Invalid room name or password!')
    return render_template('join_room.html', form=form)

@bp.route('/room/<int:room_id>')
@login_required
def room(room_id):
    room = Room.query.get_or_404(room_id)
    return render_template('room.html', room=room)

import datetime  # Upewnij się, że moduł datetime jest poprawnie zaimportowany
import random
import string

@bp.route('/play_game/<int:room_id>')
@login_required
def play_game(room_id):
    room = Room.query.get_or_404(room_id)
    if current_user not in room.users:
        return redirect(url_for('game.room', room_id=room_id))
    
    random_number = random.randint(3, 8)
    first_random_letter = random.choice(string.ascii_lowercase)
    second_random_letter = random.choice(string.ascii_lowercase)

    start_time = request.args.get('start_time', datetime.datetime.now().isoformat())
    return render_template('game.html', room=room, start_time=start_time, random_number = random_number,
                           first_random_letter = first_random_letter, second_random_letter=second_random_letter)


@bp.route('/end_game/<int:room_id>')
@login_required
def end_game(room_id):
    room = Room.query.get_or_404(room_id)
    return redirect(url_for('game.room', room_id=room_id))

@bp.route('/home')
def home():
    return render_template('home.html')

@bp.route('/instruction')
def instruction():
    return render_template('instruction.html')

@bp.route('/about')
def about():
    return render_template('about.html')


from flask_socketio import join_room

@socketio.on('join')
def handle_join(data):
    room_id = data['room']
    join_room(room_id)
    room = Room.query.get(room_id)
    socketio.emit('user_update', {'users': [{'username': user.username, 'points': user.points} for user in room.users]}, to=room_id)

from flask_socketio import leave_room

@socketio.on('leave')
def handle_leave(data):
    room_id = data['room']
    leave_room(room_id)
    room = Room.query.get(room_id)
    if room:
        room.users.remove(current_user)
    current_user.points = 0
    db.session.commit()
    if(room):
        socketio.emit('user_update', {'users': [{'username': user.username, 'points': user.points} for user in room.users]}, to=room_id)
        if current_user == room.owner:
            socketio.emit('redirect_to_home', {'url': url_for('game.home')}, to=room_id)
            db.session.delete(room)
            db.session.commit()
        

@socketio.on('start_game')
def handle_start_game(data):
    room_id = data['room']
    print(f"Start game for room {room_id}")
    socketio.emit('redirect_to_game', {'url': url_for('game.play_game', room_id=room_id)}, to=room_id)

@socketio.on('submit_points')
def handle_submit_points(data):
    time_percentage = float(data['timePercentage'])
    answer = data['answer']
    letter_number = int(data['random_number'])
    first_required_letter = data['first_random_letter']
    second_required_letter = data['second_random_letter']
    print(is_english_word(answer))
    if is_english_word(answer) and len(answer) == letter_number and first_required_letter in answer and second_required_letter in answer:
        current_user.points += int(time_percentage*100)
    db.session.commit()

app/templates/about.html
{% extends "base.html" %}
{% block title %}Instructions{% endblock %}
{% block content %}
<script>
    jQuery(document).ready(function(){
    $('#cont').mousemove(function(e){
        var rXP = (e.pageX - this.offsetLeft-$(this).width()/2);
        var rYP = (e.pageY - this.offsetTop-$(this).height()/2);
        $('#bored').css('text-shadow', +rYP/10+'px '+rXP/80+'px rgba(109, 16, 113,.8), '+rYP/8+'px '+rXP/60+'px rgba(252, 130, 246, 0.6), '+rXP/70+'px '+rYP/12+'px rgba(30, 7, 92,.7)');
        });
    });
</script>
  <div class="row min-vh-100">
    <div class="col d-flex flex-column justify-content-center align-items-center">
      <div class="row text-center border border-3 p-4" id="square2">
        <h1 style="font-size: 50px;">About us</h1>
        <p>
            This website was created by students of AGH University of Krakow. 
            Any questions can be directed to the university, but I doubt there will be any. 
            After all, the site is non-public :).  <div id="bored">Have fun with the game!</div>
        </p>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> 
  <title>{% block title %}{% endblock %}</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
  <div class="nav-container" id="nav-container">
    <nav class="navbar navbar-expand-lg navbar-dark p-2 fixed-top" id="navbar">
      <h1 class="d-flex navbar-brand align-items-center fs-1 fw-bold">
          Password Game
      </h1>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#rooms" aria-controls="#rooms" aria-expanded="false" aria-label="Toggle navigation" id="navbar-toggler">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="rooms">
          <ul class="navbar-nav fs-4 me-auto" id="navbarNav">
            <li class="nav-item">
              <a class="nav-link fs-4" href="{{ url_for('game.home') }}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link fs-4" href="{{ url_for('game.join_room') }}">Join</a>
            </li>
            <li class="nav-item">
              <a class="nav-link fs-4" href="{{ url_for('game.create_room') }}">Create</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" role="button"  data-bs-toggle="dropdown" aria-expanded="false">
                Help
              </a>
              <ul class="dropdown-menu" id="dropdown">
                <li><a class="dropdown-item" href="{{ url_for('game.instruction') }}">Instruction</a></li>
                <li><a class="dropdown-item" href="{{ url_for('game.about') }}">About us</a></li>
              </ul>
            </li>
          </ul>
          <ul class="navbar-nav fs-5 ms-auto" id="navbarNav">
            {% if current_user.is_authenticated %}
              <li class="nav-item pe-2">
                <a class="btn btn-secondary fs-5" style="background-color: rgba(254, 251, 253, 0.3);" href="{{ url_for('auth.logout') }}">Logout</a>
              </li>
            {% else %}
              <li class="nav-item pe-2">
                <a class="btn btn-secondary fs-5" style="background-color: rgba(254, 251, 253, 0.8); color: rgb(30, 7, 92);" href="{{ url_for('auth.login') }}">Login</a>
              </li>
              <li class="nav-item">
                <a class="btn btn-secondary fs-5" style="background-color: rgba(254, 251, 253, 0.3);" href="{{ url_for('auth.register') }}">Register</a>
              </li>
            {% endif %}
          </ul>
      </div>
    </nav>
  </div>   
  <div class="container-fluid min-vh-100" id="cont">
    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul class="flashes">
          {% for message in messages %}
            <li>{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
  </div>
</body>
</html>

app/templates/create_room.html
{% extends "base.html" %}
{% block title %}Create Room{% endblock %}
{% block content %}
  <div class="row vh-100">
    <div class="col d-flex flex-column justify-content-center align-items-center">
      <div class="row text-center border border-3 p-4" id="square">
        <h2>Create Room</h2>
        <form method="POST" action="">
          {{ form.hidden_tag() }}
          <p>
            {{ form.name.label }}<br>
            {{ form.name(style="width: 80%") }}<br>
          </p>
          <p>
            {{ form.password.label }}<br>
            {{ form.password(style="width: 80%") }}<br>
          </p>
          <p>{{ form.submit(class="btn active", style="background-color: rgb(93, 0, 215, 0.6); border-color: rgb(93, 0, 215); color: white; font-size: 25px;") }}</p>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/game.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
  <div class="row h-100" style="padding-top: 100px;">
    <div class="container d-flex align-items-center">
        <h1 class="flex-shrink-1 me-4" id="game-on">Game is on!</h1>
        <div class="progress flex-grow-1" id="progress-bar-container">
            <div class="progress-bar bg-secondary progress-bar-striped progress-bar-animated border border-light" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" id="progress-bar">30s</div>
        </div>
    </div>
    <div class="col">
        <div class="row d-flex flex-row justify-content-evenly" id='requirements'>
            <div class="text-center border border-3 px-4" id="req">
                Your password must be {{random_number}} characters long.
            </div>
            <div class="text-center border border-3 px-4" id="req">
                Your password must contain the letter "{{first_random_letter}}".
            </div>
            <div class="text-center border border-3 px-4" id="req">
                Yout password must contain the letter "{{second_random_letter}}".
            </div>
        </div>
    </div>
    <div style="display: flex;" id='answer'>
        <div class="form-floating flex-grow-1 mx-3 ms-5 mb-5">
            <input type="text" class="form-control" id="word" name="word" placeholder="word">
            <label for="word">Your answer</label>
        </div>
        <button class="btn btn-secondary mx-4 me-5 mb-5" id="submit">Submit</button>
    </div>

    <script>
        var flag = true;
        window.addEventListener('beforeunload', function(event) {
            console.log(flag);
            flag = true;
        })
        // Retrieve timeLeft from localStorage if available, otherwise initialize
        let timeLeft = localStorage.getItem('timeLeft') || 30;
        const progressBar = document.getElementById('progress-bar');

        const timer = setInterval(function() {
            timeLeft--;
            progressBar.style.width = `${(timeLeft / 30) * 100}%`;
            progressBar.textContent = `${timeLeft}s`;

            // Store timeLeft in localStorage
            localStorage.setItem('timeLeft', timeLeft);

            if (timeLeft <= 0) {
                flag = false
                localStorage.setItem('timeLeft', timeLeft);
                clearInterval(timer);
                window.location.href = "{{ url_for('game.end_game', room_id=room.id) }}";
            }
        }, 1000);

        // Check if the form was already submitted
        if (localStorage.getItem('formSubmitted') === 'true') {
            document.getElementById('answer').style.display = 'none';
        }

        var roomId = "{{ room.id }}";
        var socket = io();

        document.addEventListener('DOMContentLoaded', function() {
            var pointsForm = document.getElementById('submit');
            if (pointsForm) {
                pointsForm.addEventListener('click', function(event) {
                    var timePercentage = localStorage.getItem('timeLeft') / 30;
                    var answer = document.getElementById('word').value;
                    socket.emit('submit_points', { room: roomId, timePercentage: timePercentage, random_number: "{{random_number}}",
                        first_random_letter: "{{first_random_letter}}", second_random_letter: "{{second_random_letter}}", answer: answer });
                    document.getElementById('word').value = '';  // Clear the input field after submission
                    document.getElementById('answer').style.display = 'none';

                    // Save the form submission state
                    localStorage.setItem('formSubmitted', 'true');
                });
            }
        });
    </script>
  </div>
{% endblock %}

app/templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
  <div class="row h-100" style="padding-top: 100px;">
    <div class="col-md-5 text-center">
      <p id="shout">Play with your friends!</p>
    </div>
    <div class="col-md-7 text-center d-flex flex-column justify-content-center align-items-center">
      <h1 id="home_h1">Create or join a room to play a password puzzle game.</h1>
      <p id="home_desc">
        - You will be given three requirements that your password must contain. <br>
        - Answers must be provided within a specified time. <br>
        - Your results will be displayed in the table at the end of each round.
      </p>
      <div>
        <a class="btn btn-secondary" id="home_btn" href="{{ url_for('game.create_room') }}" style="margin-right: 30px;">Create</a>
        <a class="btn btn-secondary" id="home_btn" href="{{ url_for('game.join_room') }}">Join</a>
      </div>  
    </div>
  </div>
{% endblock %}

app/templates/instruction.html
{% extends "base.html" %}
{% block title %}Instructions{% endblock %}
{% block content %}
  <div class="row min-vh-100">
    <div class="col d-flex flex-column justify-content-center align-items-center">
      <div class="row text-center border border-3 p-4" id="square">
        <h2>How to play?</h2>
        <p>
            - Log in or create an acccount if you don't have one yet. <br>
            - Create a room or join an existing one. In both cases you will need a room name and password. <br>
            - Wait for other players to join. <br>
            - When everyone is ready, the room owner (the person who created it) will start the game. <br>
            - Three requirements will be given after the start of the game. <br>
            - Your task is to create a password (word) that meets these requirements. <br>
            - The results will be displayed at the end of each round that lasts 30s.
        </p>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/join_room.html
{% extends "base.html" %}
{% block title %}Join Room{% endblock %}
{% block content %}
  <div class="row vh-100">
    <div class="col d-flex flex-column justify-content-center align-items-center">
      <div class="row text-center border border-3 p-4" id="square">
        <h2>Join Room</h2>
        <form method="POST" action="">
          {{ form.hidden_tag() }}
          <p>
            {{ form.name.label }}<br>
            {{ form.name(style="width: 80%") }}<br>
          </p>
          <p>
            {{ form.password.label }}<br>
            {{ form.password(style="width: 80%") }}<br>
          </p>
          <p>{{ form.submit(class="btn active", style="background-color: rgb(93, 0, 215, 0.6); border-color: rgb(93, 0, 215); color: white; font-size: 25px;") }}</p>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
  <div class="row vh-100">
    <div class="col d-flex flex-column justify-content-center align-items-center">
      <div class="row text-center border border-3 p-4" id="square">
        <h2>Login</h2>
        <form method="POST" action="">
          {{ form.hidden_tag() }}
          <p>
            {{ form.username.label }}<br>
            {{ form.username(style="width: 80%;") }}<br>
          </p>
          <p>
            {{ form.password.label }}<br>
            {{ form.password(style="width: 80%;") }}<br>
          </p>
          <p>
            {{ form.remember() }} {{ form.remember.label }}
          </p>
          <p>{{ form.submit(class="btn active", style="background-color: rgb(93, 0, 215, 0.6); border-color: rgb(93, 0, 215); color: white;") }}</p>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block content %}
  <div class="row vh-100">
    <div class="col d-flex flex-column justify-content-center align-items-center">
      <div class="row text-center border border-3 p-4" id="square">
        <h2>Register</h2>
        <form method="POST" action="">
          {{ form.hidden_tag() }}
          <p>
            {{ form.username.label }}<br>
            {{ form.username(style="width: 80%;") }}<br>
          </p>
          <p>
            {{ form.password.label }}<br>
            {{ form.password(style="width: 80%;") }}<br>
          </p>
          <p>{{ form.submit(class="btn active", style="background-color: rgb(93, 0, 215, 0.6); border-color: rgb(93, 0, 215); color: white;") }}</p>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/room.html
{% extends "base.html" %}
{% block title %}Room{% endblock %}
{% block content %}
<script>
    jQuery(document).ready(function(){
    $('#cont').mousemove(function(e){
        var rXP = (e.pageX - this.offsetLeft-$(this).width()/2);
        var rYP = (e.pageY - this.offsetTop-$(this).height()/2);
        $('#roomn').css('text-shadow', +rYP/10+'px '+rXP/80+'px rgba(109, 16, 113,.8), '+rYP/8+'px '+rXP/60+'px rgba(252, 130, 246, 0.6), '+rXP/70+'px '+rYP/12+'px rgba(30, 7, 92,.7)');
        });
    });
</script>
<div class="row d-flex align-items-end" style="height: 220px;">
    <div class="col flex-column justify-content-center text-center">
        <h1 class="p-3" id="roomn">Room: {{ room.name }}</h1>
    </div>
</div>
<div class="row" style="padding-top: 20px;">
    <div class="col d-flex flex-column justify-content-center align-items-center">
        <div class="row border border-3 p-4" id="roomt">
            <h1 class="text-center">Users:</h1>
            <table class="my-3">
                <thead>
                    <tr style="background-color: rgba(254, 251, 253, 0.6);">
                        <th style="color: rgb(192, 129, 219);">Username</th>
                        <th style="color: rgb(164, 82, 228);">Points</th>
                    </tr>
                </thead>
                <tbody id="users-table">
                    {% for user in room.users %}
                        <tr>
                            <td>{{ user.username }}</td>
                            <td>{{ user.points }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            
            {% if current_user == room.owner %}
            <div class="d-flex flex-column justify-content-center align-items-center">
                <button class="btn active min-w-50 mt-2" style="background-color: rgba(254, 251, 253, 0.3);" id="start-game" data-room-id="{{ room.id }}">Start Game</button>
            </div>
            {% endif %}
            <script>
                var roomId = "{{ room.id }}";  // Przekazanie room_id do JavaScript
                var flag = true;
                window.addEventListener('beforeunload', function(event) {
                    console.log(flag);
                    if(flag == true){
                        socket.emit('leave', {room: roomId});
                    }
                    flag = true;
                });
            </script>
            <script src="{{ url_for('static', filename='client.js') }}"></script>
          </div>
    </div>
</div>
{% endblock %}